version: "3"
services:
  app:
    container_name: fcm-internal-docker
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
