version: "3"
services:
  app:
    container_name: fcm-internal-docker
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - fcm_service_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: fcm_db
    ports:
      - "27017:27017"
    networks:
      - fcm_service_network

networks:
  fcm_service_network:
    external: true
