version: "3"
services:
  app:
    container_name: fcm-internal-docker
    build: .
    ports:
      - "5000:5000"
    networks:
      - fcm_service_network

  mongo:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - /mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: fcm_db
    ports:
      - "27017:27017"
    networks:
      - fcm_service_network

networks:
  fcm_service_network:
    external: true
